name: HomeTp
main: momo36.homeTp.HomeTp
version: 1.1
api-version: "1.21"
description: Simple /home, /sethome and /tpa commands with configurable options
author: aliooo36

commands:
  sethome:
    description: Save your current location as home
    usage: /sethome
    permission: hometp.sethome
  home:
    description: Teleport to your saved home
    usage: /home
    permission: hometp.home
  tpa:
    description: Teleport to another player
    usage: /tpa <player>
    permission: hometp.tpa
  tpaccept:
    description: Accept a teleport request
    usage: /tpaccept
    permission: hometp.tpa
  tpdeny:
    description: Deny a teleport request
    usage: /tpdeny
    permission: hometp.tpa
  htpconfig:
    description: Admin commands for HomeTp configuration
    usage: /htpconfig [reload|status|config]
    permission: hometp.admin

permissions:
  hometp.sethome:
    description: Allows setting a home
    default: true
  hometp.home:
    description: Allows teleporting to your home
    default: true
  hometp.tpa:
    description: Allows teleporting to another player
    default: true
  hometp.admin:
    description: Allows using admin configuration commands
    default: op